server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: abcd1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "llS8lyK4y6uEv4U/EPsghN2QEzAMZ5PGR7m8fRDngGoXLT1FV4mllNj4ht4BUlRG"